
name : "Hello Actions"
description : "Greet someone"
author : "shankalpa.lamichhane@github.com"

inputs:
  MY_NAME:
    description: "who to greet"
    required: true
    default : "world"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "mic"
  color: "purple"